"""empty message

Revision ID: c0cf71a585ec
Revises: 
Create Date: 2018-05-22 15:38:06.067611

"""
from alembic import op
import sqlalchemy as sa
import flask_fossen

# revision identifiers, used by Alembic.
revision = 'c0cf71a585ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', flask_fossen.coltypes.PasswordType(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', flask_fossen.coltypes.EmailType(length=254), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('user')
    # ### end Alembic commands ###
